/* =========================================================
   SARKARIIICHIJ
   GOVERNMENT JOB DATABASE
   ========================================================= */

window.JOBS = [

  {
    id:"ssc-cgl",
    title:"SSC CGL",
    org:"Staff Selection Commission",
    dept:"SSC",
    category:"Central Govt",
    type:"Government Job",
    state:"All India",
    status:"Active",
    vacancy:"Official Notification देखें",
    posts:"Group B & C Posts",
    qualification:"Graduate",
    age:"As per notification",
    salary:"As per post",
    fee:"As per notification",
    start:"Official Notification देखें",
    lastDate:"Official Notification देखें",
    examDate:"To Be Announced",
    notification:"https://ssc.gov.in/",
    apply:"https://ssc.gov.in/",
    official:"https://ssc.gov.in/",
    admitCard:"https://ssc.gov.in/",
    result:"https://ssc.gov.in/",
    syllabus:"https://ssc.gov.in/",
    cutoff:"#",
    papers:"#",
    details:"SSC CGL में विभिन्न Group B और Group C सरकारी पदों पर भर्ती होती है। आवेदन से पहले SSC की official notification अवश्य देखें।"
  },

  {
    id:"ssc-chsl",
    title:"SSC CHSL",
    org:"Staff Selection Commission",
    dept:"SSC",
    category:"Central Govt",
    type:"Government Job",
    state:"All India",
    status:"Active",
    vacancy:"Official Notification देखें",
    posts:"LDC / JSA / DEO",
    qualification:"12th",
    age:"As per notification",
    salary:"As per post",
    fee:"As per notification",
    start:"Official Notification देखें",
    lastDate:"Official Notification देखें",
    examDate:"To Be Announced",
    notification:"https://ssc.gov.in/",
    apply:"https://ssc.gov.in/",
    official:"https://ssc.gov.in/",
    admitCard:"https://ssc.gov.in/",
    result:"https://ssc.gov.in/",
    syllabus:"https://ssc.gov.in/",
    cutoff:"#",
    papers:"#",
    details:"SSC CHSL 12th level की central government recruitment है।"
  },

  {
    id:"ssc-mts",
    title:"SSC MTS / Havaldar",
    org:"Staff Selection Commission",
    dept:"SSC",
    category:"Central Govt",
    type:"Government Job",
    state:"All India",
    status:"Active",
    vacancy:"Official Notification देखें",
    posts:"MTS / Havaldar",
    qualification:"10th",
    age:"As per notification",
    salary:"As per post",
    fee:"As per notification",
    start:"Official Notification देखें",
    lastDate:"Official Notification देखें",
    examDate:"To Be Announced",
    notification:"https://ssc.gov.in/",
    apply:"https://ssc.gov.in/",
    official:"https://ssc.gov.in/",
    admitCard:"https://ssc.gov.in/",
    result:"https://ssc.gov.in/",
    syllabus:"https://ssc.gov.in/",
    cutoff:"#",
    papers:"#",
    details:"SSC MTS और Havaldar भर्ती 10th level candidates के लिए होती है।"
  },

  {
    id:"ssc-gd",
    title:"SSC GD Constable",
    org:"Staff Selection Commission",
    dept:"SSC",
    category:"Central Govt",
    type:"Police",
    state:"All India",
    status:"Active",
    vacancy:"Official Notification देखें",
    posts:"Constable GD",
    qualification:"10th",
    age:"As per notification",
    salary:"As per post",
    fee:"As per notification",
    start:"Official Notification देखें",
    lastDate:"Official Notification देखें",
    examDate:"To Be Announced",
    notification:"https://ssc.gov.in/",
    apply:"https://ssc.gov.in/",
    official:"https://ssc.gov.in/",
    admitCard:"https://ssc.gov.in/",
    result:"https://ssc.gov.in/",
    syllabus:"https://ssc.gov.in/",
    cutoff:"#",
    papers:"#",
    details:"SSC GD के माध्यम से CAPFs और संबंधित forces में Constable GD भर्ती होती है।"
  },

  {
    id:"ssc-cpo",
    title:"SSC CPO",
    org:"Staff Selection Commission",
    dept:"SSC",
    category:"Central Govt",
    type:"Police",
    state:"All India",
    status:"Active",
    vacancy:"Official Notification देखें",
    posts:"Sub-Inspector",
    qualification:"Graduate",
    age:"As per notification",
    salary:"As per post",
    fee:"As per notification",
    start:"Official Notification देखें",
    lastDate:"Official Notification देखें",
    examDate:"To Be Announced",
    notification:"https://ssc.gov.in/",
    apply:"https://ssc.gov.in/",
    official:"https://ssc.gov.in/",
    admitCard:"https://ssc.gov.in/",
    result:"https://ssc.gov.in/",
    syllabus:"https://ssc.gov.in/",
    cutoff:"#",
    papers:"#",
    details:"SSC CPO के माध्यम से Delhi Police और CAPFs में Sub-Inspector भर्ती होती है।"
  },

  {
    id:"rrb-ntpc",
    title:"RRB NTPC",
    org:"Railway Recruitment Boards",
    dept:"Railway",
    category:"Central Govt",
    type:"Railway",
    state:"All India",
    status:"Active",
    vacancy:"Official Notification देखें",
    posts:"Various NTPC Posts",
    qualification:"12th / Graduate",
    age:"As per notification",
    salary:"As per post",
    fee:"As per notification",
    start:"Official Notification देखें",
    lastDate:"Official Notification देखें",
    examDate:"To Be Announced",
    notification:"https://www.rrbapply.gov.in/",
    apply:"https://www.rrbapply.gov.in/",
    official:"https://www.rrbapply.gov.in/",
    admitCard:"https://www.rrbapply.gov.in/",
    result:"#",
    syllabus:"#",
    cutoff:"#",
    papers:"#",
    details:"RRB NTPC में विभिन्न Non-Technical Popular Categories के पद शामिल होते हैं।"
  },

  {
    id:"rrb-group-d",
    title:"RRB Group D",
    org:"Railway Recruitment Boards",
    dept:"Railway",
    category:"Central Govt",
    type:"Railway",
    state:"All India",
    status:"Active",
    vacancy:"Official Notification देखें",
    posts:"Level 1 Posts",
    qualification:"10th / ITI",
    age:"As per notification",
    salary:"As per post",
    fee:"As per notification",
    start:"Official Notification देखें",
    lastDate:"Official Notification देखें",
    examDate:"To Be Announced",
    notification:"https://www.rrbapply.gov.in/",
    apply:"https://www.rrbapply.gov.in/",
    official:"https://www.rrbapply.gov.in/",
    admitCard:"https://www.rrbapply.gov.in/",
    result:"#",
    syllabus:"#",
    cutoff:"#",
    papers:"#",
    details:"Railway Level 1 recruitment में विभिन्न posts शामिल हो सकती हैं।"
  },

  {
    id:"ibps-po",
    title:"IBPS PO",
    org:"Institute of Banking Personnel Selection",
    dept:"Banking",
    category:"Central Govt",
    type:"Banking",
    state:"All India",
    status:"Active",
    vacancy:"Official Notification देखें",
    posts:"Probationary Officer",
    qualification:"Graduate",
    age:"As per notification",
    salary:"As per post",
    fee:"As per notification",
    start:"Official Notification देखें",
    lastDate:"Official Notification देखें",
    examDate:"To Be Announced",
    notification:"https://www.ibps.in/",
    apply:"https://www.ibps.in/",
    official:"https://www.ibps.in/",
    admitCard:"https://www.ibps.in/",
    result:"https://www.ibps.in/",
    syllabus:"#",
    cutoff:"#",
    papers:"#",
    details:"IBPS PO public sector banks के Probationary Officer recruitment process से संबंधित परीक्षा है।"
  },

  {
    id:"sbi-po",
    title:"SBI PO",
    org:"State Bank of India",
    dept:"Banking",
    category:"Central Govt",
    type:"Banking",
    state:"All India",
    status:"Active",
    vacancy:"Official Notification देखें",
    posts:"Probationary Officer",
    qualification:"Graduate",
    age:"As per notification",
    salary:"As per post",
    fee:"As per notification",
    start:"Official Notification देखें",
    lastDate:"Official Notification देखें",
    examDate:"To Be Announced",
    notification:"https://sbi.co.in/web/careers/",
    apply:"https://sbi.co.in/web/careers/",
    official:"https://sbi.co.in/web/careers/",
    admitCard:"#",
    result:"#",
    syllabus:"#",
    cutoff:"#",
    papers:"#",
    details:"SBI PO recruitment की official जानकारी SBI Careers portal पर देखें।"
  },

  {
    id:"up-police",
    title:"UP Police",
    org:"Uttar Pradesh Police Recruitment & Promotion Board",
    dept:"Police",
    category:"State Govt",
    type:"Police",
    state:"Uttar Pradesh",
    status:"Active",
    vacancy:"Official Notification देखें",
    posts:"Various Police Posts",
    qualification:"10th / 12th / Graduate",
    age:"As per notification",
    salary:"As per post",
    fee:"As per notification",
    start:"Official Notification देखें",
    lastDate:"Official Notification देखें",
    examDate:"To Be Announced",
    notification:"https://www.uppbpb.gov.in/",
    apply:"https://www.uppbpb.gov.in/",
    official:"https://www.uppbpb.gov.in/",
    admitCard:"https://www.uppbpb.gov.in/",
    result:"https://www.uppbpb.gov.in/",
    syllabus:"#",
    cutoff:"#",
    papers:"#",
    details:"उत्तर प्रदेश पुलिस भर्ती की official notifications और updates UPPRPB portal पर देखें।"
  },

  {
    id:"uppsc-pcs",
    title:"UPPSC PCS",
    org:"Uttar Pradesh Public Service Commission",
    dept:"UPPSC",
    category:"State Govt",
    type:"Government Job",
    state:"Uttar Pradesh",
    status:"Active",
    vacancy:"Official Notification देखें",
    posts:"PCS Posts",
    qualification:"Graduate",
    age:"As per notification",
    salary:"As per post",
    fee:"As per notification",
    start:"Official Notification देखें",
    lastDate:"Official Notification देखें",
    examDate:"To Be Announced",
    notification:"https://uppsc.up.nic.in/",
    apply:"https://uppsc.up.nic.in/",
    official:"https://uppsc.up.nic.in/",
    admitCard:"https://uppsc.up.nic.in/",
    result:"https://uppsc.up.nic.in/",
    syllabus:"#",
    cutoff:"#",
    papers:"#",
    details:"UPPSC PCS उत्तर प्रदेश की प्रमुख state-level competitive recruitment examinations में से एक है।"
  },

  {
    id:"upsssc",
    title:"UPSSSC Recruitment",
    org:"Uttar Pradesh Subordinate Services Selection Commission",
    dept:"UPSSSC",
    category:"State Govt",
    type:"Government Job",
    state:"Uttar Pradesh",
    status:"Active",
    vacancy:"Official Notification देखें",
    posts:"Various Group C Posts",
    qualification:"10th / 12th / Graduate",
    age:"As per notification",
    salary:"As per post",
    fee:"As per notification",
    start:"Official Notification देखें",
    lastDate:"Official Notification देखें",
    examDate:"To Be Announced",
    notification:"https://upsssc.gov.in/",
    apply:"https://upsssc.gov.in/",
    official:"https://upsssc.gov.in/",
    admitCard:"https://upsssc.gov.in/",
    result:"https://upsssc.gov.in/",
    syllabus:"#",
    cutoff:"#",
    papers:"#",
    details:"UPSSSC उत्तर प्रदेश में विभिन्न subordinate services और Group C recruitment आयोजित करता है।"
  },

  {
    id:"army-agniveer",
    title:"Indian Army Agniveer",
    org:"Indian Army",
    dept:"Defence",
    category:"Central Govt",
    type:"Defence",
    state:"All India",
    status:"Active",
    vacancy:"Official Notification देखें",
    posts:"Agniveer",
    qualification:"10th / 12th",
    age:"As per notification",
    salary:"As per scheme",
    fee:"As per notification",
    start:"Official Notification देखें",
    lastDate:"Official Notification देखें",
    examDate:"To Be Announced",
    notification:"https://joinindianarmy.nic.in/",
    apply:"https://joinindianarmy.nic.in/",
    official:"https://joinindianarmy.nic.in/",
    admitCard:"https://joinindianarmy.nic.in/",
    result:"https://joinindianarmy.nic.in/",
    syllabus:"#",
    cutoff:"#",
    papers:"#",
    details:"Indian Army Agniveer recruitment की eligibility और notification official Army portal पर देखें।"
  },

  {
    id:"indian-navy-agniveer",
    title:"Indian Navy Agniveer",
    org:"Indian Navy",
    dept:"Defence",
    category:"Central Govt",
    type:"Defence",
    state:"All India",
    status:"Active",
    vacancy:"Official Notification देखें",
    posts:"Agniveer",
    qualification:"10th / 12th",
    age:"As per notification",
    salary:"As per scheme",
    fee:"As per notification",
    start:"Official Notification देखें",
    lastDate:"Official Notification देखें",
    examDate:"To Be Announced",
    notification:"https://www.joinindiannavy.gov.in/",
    apply:"https://www.joinindiannavy.gov.in/",
    official:"https://www.joinindiannavy.gov.in/",
    admitCard:"https://www.joinindiannavy.gov.in/",
    result:"https://www.joinindiannavy.gov.in/",
    syllabus:"#",
    cutoff:"#",
    papers:"#",
    details:"Indian Navy Agniveer recruitment की official information Navy recruitment portal पर उपलब्ध होती है।"
  },

  {
    id:"afcat",
    title:"AFCAT",
    org:"Indian Air Force",
    dept:"Defence",
    category:"Central Govt",
    type:"Defence",
    state:"All India",
    status:"Active",
    vacancy:"Official Notification देखें",
    posts:"Flying / Ground Duty",
    qualification:"Graduate",
    age:"As per notification",
    salary:"As per post",
    fee:"As per notification",
    start:"Official Notification देखें",
    lastDate:"Official Notification देखें",
    examDate:"To Be Announced",
    notification:"https://afcat.cdac.in/",
    apply:"https://afcat.cdac.in/",
    official:"https://afcat.cdac.in/",
    admitCard:"https://afcat.cdac.in/",
    result:"https://afcat.cdac.in/",
    syllabus:"#",
    cutoff:"#",
    papers:"#",
    details:"AFCAT Indian Air Force की officer-entry examination है।"
  }

];


/* =========================================================
   DATABASE FUNCTIONS
   ========================================================= */

function getJob(id){
  return window.JOBS.find(
    job => job.id === id
  );
}


function activeJobs(){
  return window.JOBS.filter(
    job => job.status === "Active"
  );
}


function searchJobs(q){

  q = String(q || "")
    .toLowerCase()
    .trim();

  if(!q){
    return window.JOBS;
  }

  return window.JOBS.filter(job => {

    return [
      job.title,
      job.org,
      job.dept,
      job.category,
      job.type,
      job.state,
      job.qualification,
      job.posts
    ]
    .join(" ")
    .toLowerCase()
    .includes(q);

  });

    }
